stages:
  - build
  - release

build:
    stage: build
    script: ./gradlew build
    cache:
        paths:
            - .gradle
            - build

jar:
    stage: release
    script: ./gradlew packageUberJarForCurrentOS
    cache:
        paths:
            - .gradle
            - build
    artifacts:
        paths:
            - "build/compose/jars/"

pkg:
    stage: release
    script: ./gradlew createDistributable
    cache:
        paths:
            - .gradle
            - build
    artifacts:
        paths:
            - "build/compose/binaries/main-release/app/"
