stages:
  - build
  - release

build:
    stage: build
    script: gradle build

jar:
    stage: release
    script: ./gradlew packageReleaseUberJarForCurrentOS
    artifacts:
        paths:
            - "build/compose/jars/"

pkg:
    stage: release
    script: ./gradlew createReleaseDistributable
    artifacts:
        paths:
            - "build/compose/binaries/main-release/app/"
