stages:
  - build
  - release

before_script:
    - apt update
    - apt install openjdk-17-jdk

build:
    stage: build
    script: ./gradlew build
    cache:
        paths:
            - .gradle
            - build

jar:
    stage: release
    script: ./gradlew packageReleaseUberJarForCurrentOS
    cache:
        paths:
            - .gradle
            - build
    artifacts:
        paths:
            - "build/compose/jars/"

pkg:
    stage: release
    script: ./gradlew createReleaseDistributable
    cache:
        paths:
            - .gradle
            - build
    artifacts:
        paths:
            - "build/compose/binaries/main-release/app/"
